[package]
name = "bin2hex"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
exitcode = "1.1.2"
hex = "0.4.3"

# from https://github.com/johnthagen/min-sized-rust
[profile.release]
strip = true
lto = true
